---
title: '<div class="jumbotron"><h1 class="title toc-ignore display-3">Participants</h1></div>'
output:
  html_document:
    includes:
      in_header: header.html
    theme: flatly
    highlight: textmate
    css: mystyle.css
pagetitle: Participants
---

```{r,echo=FALSE}
rm(list=objects()) # start with a clean workspace
```
Participants who asked to be listed. 

&nbsp;      |  &nbsp;
----|:-------------------------------------------------------------------
Laura Anderson|I'm a PhD student from the University of Queensland in the area of psychology. My research topic is predictors of adolescent sexual risk-taking, with a view to reducing STIs. I'm particularly interested in learning more about R and open science.
Rachel Bedder|I am a PhD student working in the field of Computational Psychiatry at the Max Planck UCL Centre in London. My work focuses on mood and decision-making, particularly related to symptoms of rumination and anhedonia. Looking forward to meeting you all in the sunshine!
Stephanie Black|I'm currently undertaking a PhD at UWA, investigating options to improve human performance in complex systems. I am interested in data science and research management.
Matt Blanchard|PhD student in cognitive psychology. Interested in how cognition and metacognition changes when people work in groups. Also interested in literature, surfing, bouldering and spending time in nature.
Tessel Blom|My name is Tessel and I recently started as a PhD student at the University of Melbourne, where I look at how the brain deals with its own internal delays.
Julia Caruana|I'm interested in the intersection of neuroscience, cognition, psychiatry and computational modelling. I am extremely interested in Open Science, reproducibility and integrity in psychological research. 
Srijan Chaudhary|I am a Computer Science master's student at UniMelb. My interest lies in programming in Python and Java and my research interest lies in explainable AI which deals with cognitive science and developing normative agents.
Brittany Child|I'm a first-year PhD student at the University of Adelaide. My PhD research is investigating neurocognitive function in schizophrenia, with the aim of more precisely characterising aberrant learning patterns in this disorder. In particular, I am interested in whether learning abnormalities in schizophrenia – and schizotypy more broadly – can be mapped to the basal ganglia go/no-go computational model.
Kate Coffey|
Madeleine Connolly|I have just finished my honours this year, working on an array of factor analyses of a diagnostic tool for dementia. My interests all surround how we can further our understandings of the brain and all of its functions, and then translate those findings into clinical practice. I got into psychology by way of working with teenagers with learning and/or attentional difficulties, and I hope to continue helping similar clinically relevant groups with my future research. I have particularly strong interests in impulsivity, and sustained attention in children and adolescents. 
Hannah Coyle|I am a 3rd year Clinical Neuropsychology doctoral student at Monash University. My application for the summer school was sparked by a growing interesting in data modelling within the field of psychology and its relevance and applicability to my doctoral research. My PhD thesis is investigating the relationship between changes in cortical activity and cognition following mild traumatic brain injury. My primary outcome measure is TMS-EEG, a multimodal imaging technique which combines transcranial magnetic stimulation (TMS) with electroencephalography (EEG). I am currently using the EEGLAB and TESA (an open source toolbox) in MATLAB for my data analysis.
Simon D'Alfonso|Simon D'Alfonso is a research fellow in the School of Computing and Information Systems at the University of Melbourne. He is also affiliated with eOrygen, the e-mental health group of Orygen, the National Centre of Excellence in Youth Mental Health, where he is tech lead and head of computational research. His interests include cyberpsychology, knowledge representation and applying digital technology and artificial intelligence to mental health. Webpage: [ https://people.eng.unimelb.edu.au/dalfonso]( https://people.eng.unimelb.edu.au/dalfonso) Twitter: @sjdalf
Gezelle Dali|I’m a first year PhD student with a background in cognitive neuroscience. I am interested in investigating the neurobiology of error awareness and its role in adaptive behaviour.
Ian Davies|Grad Dip Psychology student who was once an Engineer 
Michael Diamond|Psychology, Experience Sampling, Programming for Psychology, Biochemistry, Medical Research 
Sophia Garlick Bock|I have just finished my honours thesis in visual perception and have worked as a research assistant in the same field during my undergrad. Next year I will be working the next year as a full time research assistant. In my spare time I play AFL.
Bethany Growns|Postgrad student (Ph.D./M.Psyc (Forensic) Candidate) - research interests include perceptual expertise and learning, forensic decision-making, forensic expertise and expert evidence
Clare Harris|Clare is a junior medical doctor studying a Master of Philosophy (MPhil) in computational neuroscience at the Queensland Brain Institute. Supervised by Dr Marta Garrido and Dr Ilvana Dzafic, she is currently investigating regularity learning under conditions of uncertainty, volatility and threat. She hasn’t yet decided what to study in the future, but she is very interested in the neuroscience and psychology of altruism, compassion and rationality, as well as the neural correlates of pain, suffering and antisocial personality disorders.
Joel Holwerda|I am a first-year PhD student at the University of New South Wales. My research focuses on contextual factors that influence how people integrate and remember information used to make decisions. I'm also interested in other areas in cognition (e.g. language and reasoning), philosophy of science, and statistical methodology.
Angus Hughes|I am a combined PhD and Master student in Industrial and Organisational Psychology at UWA. My main interests at the moment include psychometrics and modelling of response processes, personality theory and measurement, assessment and selection, work behaviour, and methods of meta-analysis.
Danielle Iannella| My PhD thesis argued that the application of complexity theory, and its assumptions of nonlinearity, emergence and adaption, to a scenario thinking and planning process can improve decision, policy and strategy making. It included two case studies that both culminated with viable shock scenarios, one in the Australian economic system; and the second in the national security system of Australia.
Reilly Innes|I am a second year PhD student studying cognitive workload, specifically through use of the detection response task. A main highlight of my research has been working on three seperate industry collaborations focused around human factors in military applications, including training and usability of emerging technologies. 
Jonathan Januar|I'm Jon and my interests include research methods and computational approaches- especially matters regarding statistical methods and inferences. Otherwise, it's generally cute animals or musical theater.
Huw Jarvis|Huw is a PhD candidate in cognitive neuroscience at Monash University, which he began after working in clinical guideline development at the NHMRC. Huw is interested in developing mathematical models of cognition to help bridge the gap between behavioural and neuroimaging data in humans.
Matthew Jiwa|Cognitive neuroscience
Mindaugas Jurgelis|My current research focuses on the biological mechanisms of fatigue and motivation. I am interested in understanding how the subjective experience of fatigue emerges; how physical and cognitive performance declines after prolonged exertion; and the mechanisms underlying pathological fatigue in neurological disorders, such as Parkinson’s Disease. I am using computational modelling to capture behavioral processes and decision making in healthy individuals and neurological disorders.
Matthew Kaesler|I am interested in applying cognitive models to real-world problems. In particular, I use signal detection models grounded in recognition memory to better understand witness decision performance on the police lineup task. 
Zhao Hui Koh|I am a software developer and keen to involve in psychological, neuroscience-related and artificial intelligence research. 
Caroline Kuhne|I have a great love for statistics - particularly Bayesian stats, and cognitive models of decision making. Outside of the world of mathematical models of cognition, I enjoy aerial dance sports, snowboarding and playing music (albeit very poorly).
Larson Landes|
Khai Shin Lee|I am finishing my honours year in psychology, hoping to broaden my skill set in data analyses. I like music and enjoy reading in my spare time.
Amy Li|I am a fourth year psychology student at the University of New South Wales. The research I am currently working on examines the development of decision making. More broadly, my interests lie in cognitive science and its intersections with social and developmental psychology – including social cognition, conceptual development, and language learning. Outside of psychology, I’m a recovering musician, enjoy spontaneous travel, and am reliably bad at estimating how much pasta to cook for one.
Garston Liang|
Chang (Lisa) Liu|Hey, I am Lisa. I am a student in UoM, graduating from Bachelor of Science (major in Mathematical Physics). I am going to postgraduate study in Data Science next year. 
Dennis Liu|I am a PhD student in Mathematics and am interested in human behaviours and their influence on disease outbreaks, by examining digital data sets.
Pavel Lukacko|I'm an undergraduate with a love for philosophy of mind, ethics, and moral psychology. I wish to utilise knowledge from this program towards developing the most appropriate empirical methods and models for honours and postgraduate study.
Jessica Marris|I am a first-year PhD student at the University of Melbourne. My research focuses on perceptual learning, particularly in the applied context of medical education. I am investigating how to optimise perceptual training techniques to more efficiently train novices to perform complex visual tasks (e.g., identifying abnormalities in medical images). I am particularly interested in learning more about R and running online experiments. 
Marcellin Martinie|I am a PhD Candidate whose research examines different approaches for combining information from forecasters in order to produce more accurate judgments, decisions, and predictions. My research focuses on data analysis, modeling, and examining the factors that determine the best aggregation methods across a wide range of domains including politics, business, economics, sport, and psychology. I use machine learning to develop and apply my models, and evaluate them using statistical techniques such as bootstrapping and cross-validation. More generally, my research interests include cognitive modeling and statistics.
Kym McCormick|Kym is a PhD candidate in the School of Psychology, University of Adelaide. She is investigating mathematical models of eyewitness testimony outcomes under the supervision of Dr Carolyn Semmler and Professor John Dunn. She hopes to develop new identification procedures that maximise both the forensic and probative value of an eyewitness's testimony.
Angus McKerral|My research interests are around human supervision of automated vehicles and how people respond when the system fails. I'm also an avid cyclist in my spare time so I have a vested interest in making sure AVs aren't trying to run me off the road.
Ben Morgan|I’ve just finished my last semester of the graduate diploma of psychology at Melb Uni. Key interests include misinformation, cognitive biases, moral psychology, and the visualisation of data. Alongside my degree I’ve worked as a product designer, a job which entails drawing together principles and heuristics of visual communication, qualitative research insights, and patterns of behaviour drawn from analytics, in order to create accessible web services.
Bronte Morgan|I have recently completed a Bachelor of Psychology (Hons), at the University of New South Wales. I am interested in learning and cognition, particularly in the contexts of human development, and mental disorders. I am fascinated by the way in which people engage with their complex worlds, performing their own data collection that forms rich cognitive representations, to help them make efficient decisions. I am interested in how we may apply Bayesian analysis to understand both cognitive development, and cognitive disorders.
Kelsey Moty|I’m a PhD student in psychology at New York University. I’m interested in how kids learn about categories: what they infer about categories from language/pragmatic context, and the consequences of these inferences for how they think about categories. 
Katie Munt|I’m a first year PhD student from The University of Queensland. My PhD research is in the area of followership but I am interested in many aspects of organisational and social psychology including leadership, health and well-being, social identity, and prosocial behaviour, to name a few.
David Mussoff|Emotions, Clinical Psych, Personality, Cognition, Momentary Awareness
Dan Myles|I began my PhD at BMH in 2017 under the supervision of Associate Professor Adrian Carter and Professor Murat Yücel at Monash University. My thesis considers how the pokies are designed to influence human cognition to promote extended or repeated play. My research also explores how different explanations for gambling harm may influence public perceptions of gambling, ideas about who is responsible for gambling harm, stigma towards gamblers, as well as support for regulatory strategies that aim to mitigate gambling-related harm.
David Ng|I just finished my Psych Honours at UNSW comparing animal/associative and human/cognitive models of generalization. I'm planning to do a PHD on how we can reduce people's beliefs in pseudosciences. I'm attending the University of Melbourne coding party as I analysed my Honours data in R and fell in love with all things coding. I hope this will also help me on a silly side project with friends involving teaching an AI how to be a jerk by learning from mean tweets and subreddits. Outside of nerdy uni stuff I like fishkeeping, computer games, hip-hop/rap music, and Muay Thai (yeah I'm pretty much a nerdy loser in all aspects of life). 
Tess Nikitenko|I am a first year PhD (Psychology) candidate at the university of Tasmania. My research investigates the mechanisms of inhibitory control using neurophysiological methods and computational modelling supervised by Dr Mark Hinder, Prof. Andrew Heathcote and Dr Allison Matthews. I am interested in using multimodal neurophysiological methods to investigate the chronometry of inhibitory control, as well as Bayesian modelling techniques, particularly decision accumulation models and ex-gaussian race models.  My ultimate aim is to provide evidence for a new model of inhibitory control.
Julia Paterson|I am studying a Bachelor of Science and Bachelor of Computer Science double degree at Monash University, where I will be completing the extended major in psychology and specialising in data science. I hope to pursue honours and PhD research in computational neuropsychology, developing new approaches to modelling and predicting cognition and behaviour, and further investigating the clinical implications and relevance of these computational models.
Elle Pattenden|FRESH PhD student at UniMelb. Interested in cooperation, sustainability, all things birds, and trash (tv, movies, etc.). 
Rohan Puri|I am currently in the second year of my PhD at The University of Tasmania investigating the neural correlates of rapid-choice motor actions and how it is influenced by cognitive processing and healthy ageing.
Sudeshna Rajapakse|My name is Sudeshna and I'm a third year undergraduate psychology student. I have interned at the Friedreich's Ataxia and Huntington's Disease Laboratory at Monash Uni, during which I learnt how to operate Freesurfer. I dont have much expereince with R and coding in general, however, I am really eager to learn! 
Divyangana Rakesh|I'm a PhD student at the Melbourne Neuropsychiatry Centre studying Neuroscience/Neuropsychiatry. I love science, logic, literature and photography.
Roshini Randeniya|I am a PhD student investigating brain pathways and mechanisms underlying sensory learning particularly with relevance to sensory sensitivities and Autistic traits. In my study I take a Bayesian approach to understand sensory learning and use visual decision making tasks together with fMRI. 
Ashlea Rendell|I'm a PhD candidate moonlighting as a User Experience Designer with a passion for sound experimental design and mixed-methods research. Long-term I'm aiming to work in the design of digital systems and technology for improving health literacy, health care access and health-related decision making. I don't drink coffee, and have a soft spot for any dog over 30kgs.
Crystal Santos|I’m a first year PhD Candidate from the University of Queensland (Brisbane, Australia). My research investigates how our social groups influence adjustment to life in retirement. On top of that, this semester I tutored second year neuroscience and absolutely loved it!
Felix Singleton Thorn|I am working on a PhD looking at quantitative research methods in Psychology after having completed my undergraduate and Honours in Psychology at the University of Melbourne. My research examines how people plan, report and interpret the results of psychological experiments, with the goal of helping to improve the accuracy of inferences and providing practical heuristics to guide the interpretation of results.
Jennifer Sloane|My name is Jenny and I am from the States - grew up in Maryland and lived in upstate New York for a few years before moving to Sydney. I am finishing my first year as a psychology PhD student at UNSW and I am interested in studying decision making. Aside from research I love pretty much all sports, going for runs, and traveling.  
Ed Stewart|I'm a second year PhD student at UNSW. At the moment I'm looking into models of visual working memory - specifically if eye gaze data can better inform the current models in the literature. 
Jia-Xin (Jay) Tay|My main interest is in data-driven research. I aim to integrate modern prediction methods (e.g., machine learning) into organisational behavioural (OB) research in a rigorous manner that could accelerate theoretical developments.
Phoebe Thomson|I am a PhD student from the University of Melbourne based at the Murdoch Children's Institute, Royal Children's Hospital. My research is interested in  multimodal brain and cognitive development in children with ADHD and ASD. 
Yara Toenders|PhD student in Neuroscience. I focus on subtypes of depression in young people and the (neuro)biological correlates. 
Andrew Wang|I am finishing up an honours year in psychology. My main interests are in cognitive psychology, linguistics, and programming.
Joshua White|Soon-to-be psychology honours student (and ex-lawyer) interested in computational cognitive psychology, moral psychology, and the interesection between psychology, law and economics. 
Will Liheng Xu|Passionate about computational modelling in psychology. Passionate about learning, travelling, design, and life. 
Dominic Yip|Visual attention, cognitive neuroscience 
Jane Yook|Jane Yook Jeong In is a Psychology Honours student at the Australian National University, formerly from the University of Melbourne. Her research studied the neural markers involved in processing computer-generated faces relative to real faces. She is also passionate about psychopharmacology and hopes to learn more about neuropsychology. She has a diverse background, where she recently worked closely with an overseas NGO to end violence against women and children. 
Qian (Angelina) Zha|I've just completed Honours in Psychology at the University of Melbourne. I'm interested in computational modelling in cognitive psychology, especially categorisation, decision making and memory.  Next year I'm moving to Sydney. I'm going to study a Graduate Diploma in Mathematics to get a better background for doing computational modelling  and then study a PhD in computational cognitive science.
Jason Zhou|Hello, I'm Jason! My research interest is in computational models of memory and decision-making. My aim in this field is to build a comprehensive model of peoples' performance in source memory tasks. When I'm not stressing about these goals, I'm likely hounding people to play board games or enjoying a good bowl of noodles.
